apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-dash-deployment
  labels:
    app: dr-dash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dr-dash
  template:
    metadata:
      labels:
        app: dr-dash
    spec:
      containers:
      - name: dr-dash-container
        image: trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:latest
        ports:
        - containerPort: 8085
        imagePullPolicy: Always
      imagePullSecrets:
      - name: jfrog-registry-secret
