name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger on
  pull_request:
    branches:
      - main  # Or specify the branch you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v2
      with:
        registry: trialn9oork.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}   # Add your JFrog username in GitHub Secrets
        password: ${{ secrets.JFROG_API_KEY }}    # Add your JFrog API Key in GitHub Secrets

    - name: Build Docker image
      run: |
        docker build -t trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:${{ github.sha }} .
        docker tag trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:${{ github.sha }} trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:latest

    - name: Push Docker image to JFrog
      run: |
        docker push trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:${{ github.sha }}
        docker push trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app:latest
