name: Docker Image Build and Push to JFrog

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the action to trigger on (e.g., 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional but recommended for better performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to JFrog using Docker login-action
      - name: Log in to JFrog
        uses: docker/login-action@v2
        with:
          registry: trialn9oork.jfrog.io  # Your JFrog registry URL
          username: ${{ secrets.JFROG_USERNAME }}  # GitHub secret containing your JFrog username (email)
          password: ${{ secrets.JFROG_API_KEY }}  # GitHub secret containing your JFrog API key

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app .  # Replace with your repository details

      # Step 5: Push the Docker image to JFrog repository
      - name: Push Docker image to JFrog
        run: |
          docker push trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app  # Replace with your repository details

      # Step 6: Log out from JFrog (to clean up)
      - name: Logout from JFrog
        run: docker logout trialn9oork.jfrog.io
