image: python:3.9  # The base image

pipelines:
  default:
    - step:
        name: Install dependencies and run tests
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python -m unittest discover

    - step:
        name: Set up Docker and Build Docker image
        services:
          - docker  # Enable Docker service for this step
        script:
          - docker --version  # Check Docker version (optional)
          - docker build -t python-flask-app .  # Build your Docker image

    - step:
        name: Login to Docker Hub and push the image
        services:
          - docker  # Enable Docker service for this step
        script:
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Log in to Docker Hub
          - docker tag python-flask-app:latest vetri20/python-flask-app:latest  # Tag the image
          - docker push vetri20/python-flask-app:latest  # Push the image to Docker Hub

    - step:
        name: Deploy to Kubernetes
        deployment: production
        script:
          - kubectl apply -f k8s/deployment.yaml  # Apply Kubernetes deployment
