name: Docker Image Build and Push to JFrog

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional but recommended for better performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to JFrog using Docker login-action
      - name: Log in to JFrog
        uses: docker/login-action@v2
        with:
          registry: trialn9oork.jfrog.io  # Your JFrog registry URL
          username: ${{ secrets.JFROG_USERNAME }}  # GitHub secret for JFrog username
          password: ${{ secrets.JFROG_API_KEY }}  # GitHub secret for JFrog API key

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app .

      # Step 5: Push the Docker image to JFrog repository
      - name: Push Docker image to JFrog
        run: |
          docker push trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app

      # Step 6: Run the Docker container and expose correct port (8085:8085)
      - name: Run Docker container and expose port
        run: |
          docker run -d -p 8085:8085 trialn9oork.jfrog.io/dr-dash-docker-local/dr-dash-app

      # Step 7: Install Selenium and run the test
      - name: Install Selenium and run the test
        run: |
          pip install selenium webdriver-manager
          python test_selenium.py
